export const VENEZUELAN_BANKS = [
  { code: '0156', name: '100% Banco' },
  { code: '0168', name: 'Bancamiga Banco Universal, C.A.' },
  { code: '0114', name: 'Bancaribe' },
  { code: '0171', name: 'Banco Activo' },
  { code: '0128', name: 'Banco Caroní' },
  { code: '0102', name: 'Banco de Venezuela' },
  { code: '0163', name: 'Banco del Tesoro' },
  { code: '0180', name: 'Banco Digital de los Trabajadores, Banco Universal' },
  { code: '0115', name: 'Banco Exterior' },
  { code: '0151', name: 'Banco Fondo Común' },
  { code: '0105', name: 'Banco Mercantil' },
  { code: '0191', name: 'Banco Nacional de Crédito' },
  { code: '0138', name: 'Banco Plaza' },
  { code: '0137', name: 'Banco Sofitasa' },
  { code: '0104', name: 'Banco Venezolano de Crédito' },
  { code: '0172', name: 'Bancrecer' },
  { code: '0134', name: 'Banesco' },
  { code: '0177', name: 'Banfanb' },
  { code: '0146', name: 'Bangente' },
  { code: '0174', name: 'Banplus' },
  { code: '0108', name: 'BBVA Provincial' },
  { code: '0157', name: 'Delsur Banco Universal' },
  { code: '0006', name: 'Instituto Municipal de Crédito Popular' },
  { code: '0058', name: 'N58 Banco Digital Banco Microfinanciero, S.A.' },
  { code: '0004', name: 'R4 Banco Microfinanciero, C.A.' },
] as const
